version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=parser
      - POSTGRES_PASSWORD=parser
      - POSTGRES_DB=parser
    ports:
      - "5432:5432"