ALTER DEFAULT PRIVILEGES FOR ROLE parser IN SCHEMA public
    REVOKE ALL ON TABLES FROM parser;
ALTER DEFAULT PRIVILEGES FOR ROLE parser IN SCHEMA public
    REVOKE ALL ON FUNCTIONS FROM parser;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM parser;